export const anatomyPresets = {
  context: {
    label: "整体",
    selectedOrgan: "lungs",
    system: "all",
    layers: {
      skin: true,
      organs: true,
      skeleton: true,
      vessels: false,
      nerves: false,
      muscles: false,
    },
  },
  organs: {
    label: "器官",
    selectedOrgan: "heart",
    system: "all",
    layers: {
      skin: false,
      organs: true,
      skeleton: false,
      vessels: false,
      nerves: false,
      muscles: false,
    },
  },
  skeleton: {
    label: "骨骼",
    selectedOrgan: "bones",
    system: "skeletal",
    layers: {
      skin: false,
      organs: false,
      skeleton: true,
      vessels: false,
      nerves: false,
      muscles: false,
    },
  },
  muscles: {
    label: "肌肉",
    selectedOrgan: "muscles",
    system: "muscular",
    layers: {
      skin: false,
      organs: false,
      skeleton: false,
      vessels: false,
      nerves: false,
      muscles: true,
    },
  },
} as const;

export const inventoryOrgans = [
  "brain",
  "eyes",
  "ears",
  "nose",
  "mouth",
  "teeth",
  "lungs",
  "trachea",
  "heart",
  "esophagus",
  "liver",
  "stomach",
  "gallbladder",
  "pancreas",
  "small-intestine",
  "large-intestine",
  "kidneys",
  "ureters",
  "bladder",
];
